apiVersion: v1
kind: Pod
metadata:
  name: solidfire-test
  namespace: default
spec:
  restartPolicy: Never
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: solidfire-pvc
  containers:
  - name: solidfire-test
    image: "busybox"
    command: ["/bin/sh", "-c", "sleep 36000"]
    volumeMounts:
    - name: vol
      mountPath: /vol
