---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident
subjects:
  - kind: ServiceAccount
    name: trident
    namespace: default
roleRef:
  kind: ClusterRole
  name: trident
  apiGroup: rbac.authorization.k8s.io
