---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: trident.netapp.io
  name: trident
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: trident.netapp.io
